drop table REPRODUCCIO  cascade constraints;
drop table CLIENT  cascade constraints;
drop table LLISTA_CONTINGUT  cascade constraints;
drop table LLISTA  cascade constraints;
drop table ALBUM_CONTINGUT  cascade constraints;
drop table ALBUM  cascade constraints;
drop table AUTORIA  cascade constraints;
drop table CANCO  cascade constraints;
drop table PRODUCTE  cascade constraints;
drop table H_GRUP  cascade constraints;
drop table ART_IND  cascade constraints;
drop table ART_GRUP  cascade constraints;
drop table ARTISTA  cascade constraints;
drop table ESTIL  cascade constraints;
drop table PAIS  cascade constraints;



CREATE TABLE PAIS --correcte
(
	pai_codi_iso CHAR(2),
	pai_nom VARCHAR2(64) NOT NULL,
	CONSTRAINT pk_PAIS PRIMARY KEY (pai_codi_iso),
	CONSTRAINT un_pai_nom UNIQUE (pai_nom)
);

CREATE TABLE ESTIL --correcte
(
	est_id NUMBER(4) GENERATED ALWAYS AS IDENTITY,
	est_nom VARCHAR2(64) NOT NULL,
	CONSTRAINT pk_ESTIL PRIMARY KEY (est_id),
	CONSTRAINT un_est_nom UNIQUE (est_nom)
);

CREATE TABLE ARTISTA --correcte
(
	art_id number(4) GENERATED BY DEFAULT AS IDENTITY,
	art_nom VARCHAR2(64) NOT NULL,
    art_tipus char(1) NOT NULL,
	CONSTRAINT pk_ARTISTA PRIMARY KEY (art_id),
	CONSTRAINT un_art_nom UNIQUE (art_nom),
	CONSTRAINT chk_art_tipus CHECK (art_tipus IN ('I','G'))
);

CREATE TABLE ART_GRUP --correcte
(
	grp_id number(4),
	grp_data_creacio date NOT NULL,
	CONSTRAINT pk_ART_GRUP PRIMARY KEY (grp_id),
    CONSTRAINT fk_ART_GRUP_ARTISTA FOREIGN KEY (grp_id) REFERENCES ARTISTA(art_id) 
);

CREATE TABLE ART_IND -- correcte
(
	ind_id number(4),
	ind_data_naixement date NOT NULL,
    ind_nacionalitat CHAR(2) NOT NULL, 
	CONSTRAINT pk_ART_IND PRIMARY KEY (ind_id),
	CONSTRAINT fk_ART_IND_ARTISTA FOREIGN KEY (ind_id) REFERENCES ARTISTA(art_id),
    CONSTRAINT fk_ART_IND_PAIS FOREIGN KEY (ind_nacionalitat) REFERENCES PAIS(pai_codi_iso)
); 

CREATE TABLE H_GRUP --correcte
(
	hgp_id_artgru number(4),
    hgp_id_artind number(4),
    hgp_data_inici date,
    hgp_data_final date,
	CONSTRAINT pk_H_GRUP PRIMARY KEY (hgp_id_artgru, hgp_id_artind,hgp_data_inici),
    CONSTRAINT fk_H_GRUP_ART_GRP FOREIGN KEY (hgp_id_artgru) REFERENCES ART_GRUP(grp_id),
    CONSTRAINT fk_H_GRUP_ART_IND FOREIGN KEY (hgp_id_artind) REFERENCES ART_IND(ind_id),
    CONSTRAINT chk_hgp_data_inici_hgp_data_final CHECK (hgp_data_inici < hgp_data_final)
);

CREATE TABLE PRODUCTE --correcte
(
    pro_id number(4) GENERATED BY DEFAULT AS IDENTITY,
    pro_titol varchar2(200) not null,
    pro_actiu char(1) not null,
    pro_estil number(4) not null,
    pro_tipus char(1) not null,
    CONSTRAINT pk_PRODUCTE PRIMARY KEY (pro_id),
    CONSTRAINT fk_PRODUCTE_ESTIL FOREIGN KEY (pro_estil) REFERENCES ESTIL(est_id),
    CONSTRAINT chk_cat_actiu CHECK (pro_actiu IN ('S','N')),
    CONSTRAINT chk_cat_tipus CHECK (pro_tipus IN ('C','A','L'))
);


CREATE INDEX idx_PRODUCTE_titol on PRODUCTE (pro_titol);

CREATE TABLE CANCO --correcte
(
	can_id number(4),
	can_any_creacio int NOT NULL,
    can_interpret number(4),
	can_durada int not null,
	CONSTRAINT pk_CANCO PRIMARY KEY (can_id),
    CONSTRAINT fk_CANCO_ARTISTA FOREIGN KEY (can_interpret) REFERENCES ARTISTA(art_id),
	CONSTRAINT fk_CANCO_PRODUCTE FOREIGN KEY (can_id) REFERENCES PRODUCTE(pro_id), 
	CONSTRAINT ck_CANCO_DURADA CHECK (can_durada>0)
);

CREATE TABLE AUTORIA --correcte
(
	aut_id_canco number(4),
	aut_id_artind number(4),
	CONSTRAINT pk_AUTORIA PRIMARY KEY (aut_id_canco, aut_id_artind),
    CONSTRAINT fk_AUTORIA_CANCO FOREIGN KEY (aut_id_canco) REFERENCES CANCO(can_id),
    CONSTRAINT fk_AUTORIA_ART_IND FOREIGN KEY (aut_id_artind) REFERENCES ART_IND(ind_id)
);

CREATE TABLE ALBUM --correcte
(
	alb_id number(4),
	alb_any_creacio int not null,
	alb_durada int not null,
	CONSTRAINT pk_ALBUM PRIMARY KEY (alb_id),
    CONSTRAINT fk_ALBUM_PRODUCTE FOREIGN KEY (alb_id) REFERENCES PRODUCTE(pro_id),
	CONSTRAINT ck_ALBUM_durada check (alb_durada>=0)
);

CREATE TABLE ALBUM_CONTINGUT --correcte
(
	alc_id_album number(4),
	alc_id_canco number(4),
    alc_pos number(4) not null,
	CONSTRAINT pk_ALBUM_CONTINGUT PRIMARY KEY (alc_id_album, alc_id_canco),
    CONSTRAINT fk_ALBUM_CONTINGUT_ALBUM FOREIGN KEY (alc_id_album) REFERENCES ALBUM(alb_id),
    CONSTRAINT fk_ALBUM_CONTINGUT_CANCO FOREIGN KEY (alc_id_canco) REFERENCES CANCO(can_id),
    CONSTRAINT un_alc_id_album_alc_pos UNIQUE (alc_id_album, alc_pos),
    CONSTRAINT chk_alc_pos CHECK (alc_pos > 0)
);

CREATE TABLE LLISTA --correcte
(
	lis_id number(4),
	lis_durada int not null,
	CONSTRAINT pk_LLISTA PRIMARY KEY (lis_id),
    CONSTRAINT fk_LLISTA_PRODUCTE FOREIGN KEY (lis_id) REFERENCES PRODUCTE(pro_id),
	CONSTRAINT ck_LLISTA_durada check(lis_durada>=0)
);

CREATE TABLE LLISTA_CONTINGUT --correcte
(
	lic_id_llista number(4),
	lic_id_PRODUCTE number(4),
    lic_pos number(4) not null,
	CONSTRAINT pk_LLISTA_PRODUCTE PRIMARY KEY (lic_id_llista, lic_id_PRODUCTE),
    CONSTRAINT fk_LLISTA_PRODUCTE_LLISTA FOREIGN KEY (lic_id_llista) REFERENCES LLISTA(lis_id),
    CONSTRAINT fk_LLISTA_PRODUCTE_PRODUCTE FOREIGN KEY (lic_id_PRODUCTE) REFERENCES PRODUCTE(pro_id) ,
    CONSTRAINT un_lic_id_LLISTA_lic_pos UNIQUE (lic_id_llista, lic_pos),
    CONSTRAINT chk_lic_pos CHECK (lic_pos > 0)
);

CREATE TABLE CLIENT --correcte
(
	cli_id number(4) GENERATED BY DEFAULT AS IDENTITY,
	cli_email varchar2(100) not null,
    cli_nom varchar2(100) not null,
    cli_cognoms varchar2(100) not null,
    cli_data_naixement date not null,
    cli_c_postal varchar2(10) not null,
    cli_dom1 varchar2(100) not null,
    cli_dom2 varchar2(100),
    cli_poblacio varchar2(200) not null,
    cli_pais char(2) not null,
	CONSTRAINT pk_CLIENT PRIMARY KEY (cli_id),
    CONSTRAINT fk_CLIENT_PAIS FOREIGN KEY (cli_pais) REFERENCES PAIS(pai_codi_iso),
    CONSTRAINT un_cli_email UNIQUE (cli_email)
);

create index idx_client_cognoms_nom on client (cli_cognoms, cli_nom);

CREATE TABLE REPRODUCCIO
(
	rep_id_client number(4),
	rep_moment_temporal date,
    rep_id_producte number(4) not null,
	CONSTRAINT pk_REPRODUCCIO PRIMARY KEY (rep_id_client, rep_moment_temporal),
    CONSTRAINT fk_REPRODUCCIO_CLIENT FOREIGN KEY (rep_id_client) REFERENCES CLIENT(cli_id),
    CONSTRAINT fk_REPRODUCCIO_PRODUCTE FOREIGN KEY (rep_id_producte) REFERENCES PRODUCTE(pro_id)
);


---Triggers---
/
CREATE or replace TRIGGER trigger_grp_data_creacio
   before insert or update on ART_GRUP
   for each row
BEGIN
  IF (sysdate < :new.grp_data_creacio)
  THEN
    RAISE_APPLICATION_ERROR(-20001,'la data de creacio no pot ser futura');
  END IF;
END;
/
create or replace TRIGGER trigger_ind_data_naixement
   before insert or update on ART_IND
   for each row
BEGIN
  IF (sysdate < :new.ind_data_naixement) THEN
    RAISE_APPLICATION_ERROR(-20002,'la data de naixement no pot ser futura');
  END IF;
END;
/
create or replace TRIGGER trigger_can_any_creacio
   before insert or update on CANCO
   for each row
BEGIN
  IF (to_number(to_char(sysdate, 'YYYY')) < :new.can_any_creacio) THEN
    RAISE_APPLICATION_ERROR(-20003,'la data de creacio de la canço no pot ser futura');
  END IF;
END;
/
create or replace TRIGGER trigger_alb_any_creacio
   before insert or update on ALBUM
   for each row
BEGIN
  IF (to_number(to_char(sysdate, 'YYYY')) < :new.alb_any_creacio) THEN
    RAISE_APPLICATION_ERROR(-20004,'la data de creacio del album no pot ser futura');
  END IF;
END;
/
create or replace TRIGGER trigger_hgp_data_inici
   before insert or update on H_GRUP
   for each row
BEGIN
  IF (sysdate < :new.hgp_data_inici) THEN
     RAISE_APPLICATION_ERROR(-20005,'la data de inici del grup no pot ser futura');
  END IF;
END;


/
CREATE or replace TRIGGER trigger_grp_moment_temporal
   before insert or update on REPRODUCCIO
   for each row
BEGIN
  IF (sysdate < :new.rep_moment_temporal)
  THEN
    RAISE_APPLICATION_ERROR(-200012,'El moment temporal no pot ser futur');
  END IF;
END;
/

create or replace TRIGGER trigger_can_durada
   before insert or update on CANCO
   for each row
BEGIN
	IF (:new.can_durada <=0) THEN
		RAISE_APPLICATION_ERROR(-20006,'La durada no pot ser 0 o mes petit');
	end if;
END;
/

create or replace TRIGGER trigger_llista_durada
   before insert or update on LLISTA
   for each row
BEGIN
	IF (:new.lis_durada <0) THEN
		RAISE_APPLICATION_ERROR(-20007,'La durada no pot ser 0 o mes petit');
	end if;
END;
/

create or replace TRIGGER trigger_album_durada
   before insert or update on ALBUM
   for each row
BEGIN
	IF (:new.alb_durada <0) THEN
		RAISE_APPLICATION_ERROR(-20008,'La durada no pot ser 0 o mes petit');
	end if;
END;
/



create or replace TRIGGER trigger_clivi_del
	before delete on CLIENT
    for each row
BEGIN
	if (:old.cli_id = 0) then 
		 RAISE_APPLICATION_ERROR(-20008,'No es pot eliminar el client virtual');
	end if;
END;
/
create or replace TRIGGER trigger_llista_tipus
	before INSERT or UPDATE ON LLISTA
	for each row
DECLARE
  v_tipus producte.pro_tipus%type;
BEGIN
	select pro_tipus into v_tipus from PRODUCTE where pro_id = :new.lis_id;
	if (v_tipus != 'L') then
		 RAISE_APPLICATION_ERROR(-20009,'No pots inserir una llista dintre de una llista');
	end if;
END;
/
create or replace TRIGGER trigger_del_client
	before delete on CLIENT
    FOR EACH ROW
DECLARE
	qt_repr number;
BEGIN
	select count(*) into qt_repr from REPRODUCCIO repr where repr.rep_id_client = :old.cli_id;
	if(qt_repr>0)THEN
		update REPRODUCCIO set rep_id_client = 0 where rep_id_client = :old.cli_id;
	end IF;
END;
/
create or replace TRIGGER trigger_del_prod
before delete on PRODUCTE
  FOR EACH ROW
DECLARE
	qt_repr number;
BEGIN
	select count(*) into qt_repr from PRODUCTE  where :old.pro_id IN (select rep_id_producte from REPRODUCCIO);
	if(qt_repr>0)THEN
		RAISE_APPLICATION_ERROR(-20010,'No es pot eliminar un producte que te reproduccions');
	end IF;
END;
/
create or replace TRIGGER trigger_del_artist
before delete on ARTISTA
  FOR EACH ROW
DECLARE 
	qt1 number;
	qt2 number;
BEGIN
	select count(*) into qt1 from CANCO can where can.can_interpret = :old.art_id;
	select count(*) into qt2 from AUTORIA aut where aut.aut_id_artind = :old.art_id;
	
	if(qt1>0 or qt2>0) then
		RAISE_APPLICATION_ERROR(-20011,'No es pot eliminar un artista que es autor o interpret de cancons');
	end if;
END;


/

create or replace trigger trigger_durada_album_contingut
after insert or delete or update of alc_id_canco
on ALBUM_CONTINGUT
for each ROW
declare 
v_durada number(6);
v_tipus char(1);
begin
	if inserting or updating THEN
		select pro_tipus into v_tipus from PRODUCTE where pro_id = :new.alc_id_canco;
		if v_tipus = 'C' THEN
			select can_durada into v_durada from CANCO where can_id = :new.alc_id_canco;
			update album set alb_durada = alb_durada + v_durada where alb_id = :new.alc_id_album;
		end if;
	end if;	
	
	if deleting or updating THEN
		select pro_tipus into v_tipus from PRODUCTE where pro_id = :old.alc_id_canco;
		if v_tipus = 'C' THEN
			select can_durada into v_durada from CANCO where can_id = :old.alc_id_canco;
			update album set alb_durada = alb_durada - v_durada where alb_id = :old.alc_id_album;
		end if;
	end if;	
end;
/



create or replace trigger trigger_durada_album_aft_update_dur_canco
after update of can_durada on CANCO
for each ROW
BEGIN

	update album
	set alb_durada = alb_durada - :old.can_durada + :new.can_durada
	where alb_id in (select alc_id_album
				   from album_contingut
				   where alc_id_canco = :old.can_id);
END;

/

create or replace trigger trigger_durada_llista_contingut
after insert or delete or update of lic_id_PRODUCTE
on LLISTA_CONTINGUT
for each ROW
declare 
v_durada number(6);
v_tipus char(1);
begin
	if inserting or updating THEN
		select pro_tipus into v_tipus from PRODUCTE where pro_id = :new.lic_id_PRODUCTE;
		if v_tipus = 'C' THEN
			select can_durada into v_durada from CANCO where can_id = :new.lic_id_PRODUCTE;
			update llista set lis_durada = lis_durada + v_durada where lis_id = :new.lic_id_llista;
		end if;
		if v_tipus = 'A' THEN
			select alb_durada into v_durada from album where alb_id = :new.lic_id_PRODUCTE;
			update llista set lis_durada = lis_durada + v_durada where lis_id = :new.lic_id_llista;
		end if;	
	end if;	

	if deleting or updating THEN
		select pro_tipus into v_tipus from PRODUCTE where pro_id = :old.lic_id_PRODUCTE;
		if v_tipus = 'C' THEN
			select can_durada into v_durada from CANCO where can_id = :old.lic_id_PRODUCTE;
			update llista set lis_durada = lis_durada - v_durada where lis_id = :old.lic_id_llista;
		end if;
		if v_tipus = 'A' THEN
			select alb_durada into v_durada from album where alb_id = :old.lic_id_PRODUCTE;
			update llista set lis_durada = lis_durada - v_durada where lis_id = :old.lic_id_llista;
		end if;	
	end if;	
end;

/

create or replace trigger trigger_durada_llista_aft_update_dur_canco
after update of can_durada on CANCO
for each ROW
BEGIN

	update llista
	set lis_durada = lis_durada - :old.can_durada + :new.can_durada
	where lis_id in (select lic_id_llista
				   from LLISTA_CONTINGUT
				   where lic_id_PRODUCTE = :old.can_id);
END;
/

create or replace trigger trigger_durada_llista_aft_update_dur_album
after update of alb_durada on album
for each ROW
BEGIN

	update llista
	set lis_durada = lis_durada - :old.alb_durada + :new.alb_durada
	where lis_id in (select lic_id_llista
				   from LLISTA_CONTINGUT
				   where lic_id_PRODUCTE = :old.alb_id);
END;
/


INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AF', 'Afganistan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AL', 'Albània');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('DE', 'Alemanya');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('DZ', 'Algèria');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AD', 'Andorra');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AO', 'Angola');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AI', 'Anguilla');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AQ', 'Antàrtida');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AG', 'Antigua i Barbuda');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SA', 'Aràbia Saudita');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AR', 'Argentina');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AM', 'Armènia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AW', 'Aruba');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AU', 'Austràlia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AT', 'Àustria');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AZ', 'Azerbaidjan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BS', 'Bahames');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BH', 'Bahrain');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BD', 'Bangladesh');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BB', 'Barbados');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BY', 'Belarús');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BE', 'Bèlgica');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BZ', 'Belize');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BJ', 'Benín');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BM', 'Bermudes');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BT', 'Bhutan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BO', 'Bolívia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BA', 'Bòsnia i Hercegovina');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BW', 'Botswana');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BV', 'Bouvet');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BR', 'Brasil');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BN', 'Brunei');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BG', 'Bulgària');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BF', 'Burkina Faso');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BI', 'Burundi');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KH', 'Cambodja');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CM', 'Camerun');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CA', 'Canadà');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CV', 'Cap Verd');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BQ', 'Carib Neerlandès');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('VA', 'Ciutat del Vaticà');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CO', 'Colòmbia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KM', 'Comores');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KP', 'Corea del Nord');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KR', 'Corea del Sud');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CR', 'Costa Rica');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('HR', 'Croàcia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CU', 'Cuba');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CW', 'Curaçao');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('DK', 'Dinamarca');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('DJ', 'Djibouti');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('DM', 'Dominica');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('EG', 'Egipte');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SV', 'El Salvador');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AE', 'Emirats Àrabs Units');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('EC', 'Equador');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ER', 'Eritrea');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SK', 'Eslovàquia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SI', 'Eslovènia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ES', 'Espanya');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('US', 'Estats Units');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('EE', 'Estònia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SZ', 'eSwatini');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ET', 'Etiòpia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('FJ', 'Fiji');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PH', 'Filipines');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('FI', 'Finlàndia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('FR', 'França');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GA', 'Gabon');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GM', 'Gàmbia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GE', 'Geòrgia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GH', 'Ghana');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GI', 'Gibraltar');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GR', 'Grècia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GD', 'Grenada');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GL', 'Groenlàndia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GP', 'Guadeloupe');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GF', 'Guaiana Francesa');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GU', 'Guam');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GT', 'Guatemala');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GG', 'Guernsey');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GN', 'Guinea');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GW', 'Guinea Bissau');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GQ', 'Guinea Equatorial');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GY', 'Guyana');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('HT', 'Haití');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('HN', 'Hondures');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('HK', 'Hong Kong (RAE Xina)');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('HU', 'Hongria');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('YE', 'Iemen');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CX', 'Illa Christmas');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('RE', 'Illa de la Reunió');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IM', 'Illa de Man');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('HM', 'Illa Heard i Illes McDonald');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AX', 'Illes Åland');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KY', 'Illes Caiman');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CC', 'Illes Cocos');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CK', 'Illes Cook');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('FO', 'Illes Fèroe');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GS', 'Illes Geòrgia del Sud i Sandwich del Sud');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('FK', 'Illes Malvines');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MP', 'Illes Mariannes del Nord');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MH', 'Illes Marshall');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('UM', 'Illes Perifèriques Menors dels EUA');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PN', 'Illes Pitcairn');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SB', 'Illes Salomó');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TC', 'Illes Turks i Caicos');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('VG', 'Illes Verges Britàniques');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('VI', 'Illes Verges Nord-americanes');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IN', 'Índia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ID', 'Indonèsia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IR', 'Iran');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IQ', 'Iraq');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IE', 'Irlanda');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IS', 'Islàndia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IL', 'Israel');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IT', 'Itàlia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('JM', 'Jamaica');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('JP', 'Japó');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('JE', 'Jersey');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('JO', 'Jordània');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KZ', 'Kazakhstan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KE', 'Kenya');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KG', 'Kirguizistan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KI', 'Kiribati');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KW', 'Kuwait');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LA', 'Laos');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LS', 'Lesotho');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LV', 'Letònia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LB', 'Líban');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LR', 'Libèria');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LY', 'Líbia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LI', 'Liechtenstein');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LT', 'Lituània');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LU', 'Luxemburg');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MO', 'Macau (RAE Xina)');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MK', 'Macedònia del Nord');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MG', 'Madagascar');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MY', 'Malàisia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MW', 'Malawi');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MV', 'Maldives');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ML', 'Mali');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MT', 'Malta');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MA', 'Marroc');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MQ', 'Martinica');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MU', 'Maurici');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MR', 'Mauritània');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('YT', 'Mayotte');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MX', 'Mèxic');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('FM', 'Micronèsia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MZ', 'Moçambic');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MD', 'Moldàvia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MC', 'Mònaco');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MN', 'Mongòlia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ME', 'Montenegro');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MS', 'Montserrat');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MM', 'Myanmar (Birmània)');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NA', 'Namíbia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NR', 'Nauru');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NP', 'Nepal');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NI', 'Nicaragua');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NE', 'Níger');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NG', 'Nigèria');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NU', 'Niue');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NF', 'Norfolk');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NO', 'Noruega');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NC', 'Nova Caledònia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NZ', 'Nova Zelanda');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('OM', 'Oman');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('NL', 'Països Baixos');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PK', 'Pakistan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PW', 'Palau');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PA', 'Panamà');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PG', 'Papua Nova Guinea');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PY', 'Paraguai');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PE', 'Perú');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PF', 'Polinèsia Francesa');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PL', 'Polònia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PT', 'Portugal');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PR', 'Puerto Rico');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('QA', 'Qatar');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('GB', 'Regne Unit');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CF', 'República Centreafricana');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ZA', 'República de Sud-àfrica');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('DO', 'República Dominicana');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('RO', 'Romania');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('RW', 'Ruanda');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('RU', 'Rússia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('EH', 'Sàhara Occidental');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('KN', 'Saint Christopher i Nevis');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SH', 'Saint Helena');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LC', 'Saint Lucia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('MF', 'Saint Martin');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('VC', 'Saint Vincent i les Grenadines');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PM', 'Saint-Pierre-et-Miquelon');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('WS', 'Samoa');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('AS', 'Samoa Nord-americana');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SM', 'San Marino');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ST', 'São Tomé i Príncipe');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SN', 'Senegal');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('RS', 'Sèrbia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SC', 'Seychelles');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SL', 'Sierra Leone');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SG', 'Singapur');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SX', 'Sint Maarten');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SY', 'Síria');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SO', 'Somàlia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('LK', 'Sri Lanka');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SD', 'Sudan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SS', 'Sudan del Sud');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SE', 'Suècia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CH', 'Suïssa');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SR', 'Surinam');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('SJ', 'Svalbard i Jan Mayen');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TJ', 'Tadjikistan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TH', 'Tailàndia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TW', 'Taiwan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TZ', 'Tanzània');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('IO', 'Territori Britànic de l’Oceà Índic');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TF', 'Territoris Australs Francesos');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('PS', 'Territoris palestins');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TL', 'Timor Oriental');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TG', 'Togo');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TK', 'Tokelau');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TO', 'Tonga');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TT', 'Trinitat i Tobago');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TN', 'Tunísia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TM', 'Turkmenistan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TR', 'Turquia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TV', 'Tuvalu');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('TD', 'Txad');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CZ', 'Txèquia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('UA', 'Ucraïna');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('UG', 'Uganda');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('UY', 'Uruguai');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('UZ', 'Uzbekistan');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('VU', 'Vanuatu');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('VE', 'Veneçuela');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('VN', 'Vietnam');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('WF', 'Wallis i Futuna');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CL', 'Xile');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CN', 'Xina');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('CY', 'Xipre');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ZM', 'Zàmbia');
INSERT INTO PAIS (pai_codi_iso, pai_nom) VALUES ('ZW', 'Zimbàbue');






--insert estils correcte --
insert into ESTIL (est_nom) values('Rock');
insert into ESTIL (est_nom) values('Pop');
insert into ESTIL (est_nom) values('Electronica');

select* from client;
--insert clients--
insert into CLIENT (cli_id,cli_email,cli_nom,cli_cognoms,cli_data_naixement,cli_c_postal,cli_dom1,cli_poblacio,cli_pais) values (0,'client0@gmail.com','Marc','Ortiz',TO_DATE('09/11/1999', 'DD/MM/YYYY'),'08700','c/Sant Palote 3 3','Igualada','ES');
insert into CLIENT (cli_email,cli_nom,cli_cognoms,cli_data_naixement,cli_c_postal,cli_dom1,cli_poblacio,cli_pais) values ('client1@gmail.com','Javier','Maravilla',TO_DATE('15/11/2000', 'DD/MM/YYYY'),'08700','c/Sant Palote 3 3','Igualada','ES');
insert into CLIENT (cli_email,cli_nom,cli_cognoms,cli_data_naixement,cli_c_postal,cli_dom1,cli_poblacio,cli_pais) values ('client2@gmail.com','Paco','Estofado',TO_DATE('23/05/1997', 'DD/MM/YYYY'),'08700','c/Sant Palote 3 3','Igualada','ES');
insert into CLIENT (cli_email,cli_nom,cli_cognoms,cli_data_naixement,cli_c_postal,cli_dom1,cli_poblacio,cli_pais) values ('client3@gmail.com','Pepe','Gotera',TO_DATE('14/06/1996', 'DD/MM/YYYY'),'08700','c/Sant Palote 3 3','Igualada','ES');

--Artistes--
insert into ARTISTA(art_nom,art_tipus) values ('Juanillo Picapiedra','I');
insert into ARTISTA(art_nom,art_tipus) values ('Pepe Botella','I');
insert into ARTISTA(art_nom,art_tipus) values ('Fran Bonilla','I');
insert into ARTISTA(art_nom,art_tipus) values ('Marco Balotelli','I');
insert into ARTISTA(art_nom,art_tipus) values ('Pablo Calvo','I');
insert into ARTISTA(art_nom,art_tipus) values ('Napoleon Bonaparte','I');
insert into ARTISTA(art_nom,art_tipus) values ('PicapiedraAndBonaparte','G');
insert into ARTISTA(art_nom,art_tipus) values ('Honolulu Lovers','G');

--Artistes individuals
insert into ART_IND(ind_id,ind_data_naixement,ind_nacionalitat) values (1,TO_DATE('09/08/1979', 'DD/MM/YYYY'),'ES');
insert into ART_IND(ind_id,ind_data_naixement,ind_nacionalitat) values (2,TO_DATE('11/09/1989', 'DD/MM/YYYY'),'ES');
insert into ART_IND(ind_id,ind_data_naixement,ind_nacionalitat) values (3,TO_DATE('04/01/1975', 'DD/MM/YYYY'),'ES');
insert into ART_IND(ind_id,ind_data_naixement,ind_nacionalitat) values (4,TO_DATE('10/05/1990', 'DD/MM/YYYY'),'ES');
insert into ART_IND(ind_id,ind_data_naixement,ind_nacionalitat) values (5,TO_DATE('11/03/1991', 'DD/MM/YYYY'),'ES');
insert into ART_IND(ind_id,ind_data_naixement,ind_nacionalitat) values (6,TO_DATE('11/12/1992', 'DD/MM/YYYY'),'ES');


--Artistes grupals
insert into ART_GRUP (grp_id,grp_data_creacio) values(7,TO_DATE('09/08/2012', 'DD/MM/YYYY'));
insert into ART_GRUP (grp_id,grp_data_creacio) values(8,TO_DATE('15/07/2014', 'DD/MM/YYYY'));



--insert producte cançons--- id;1 -12
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Starway to Heaven','S',1,'C'); --1
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('November Rain','S',1,'C'); --2
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('De Cero','S',2,'C');--3
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Diamonds','S',2,'C');--4
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Hello','S',2,'C');--5
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Highway to Hell','S',1,'C');--6


insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Party Rock Anthem','S',3,'C');--7
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Zombie','S',3,'C');--8
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Past Lives','S',3,'C');--9
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Carry on','S',1,'C');--10
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('After Dark','S',3,'C');--11
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values ('Sweet Child o Mine','S',1,'C');--12

--producte albums
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values('Showtime','S',1,'A'); -- 13
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values('Jackpot','S',2,'A'); --14

--Producte Llista--
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values('SprayAndPray','S',1,'L'); --15
insert into PRODUCTE (pro_titol,pro_actiu,pro_estil,pro_tipus) values('EzPeasyLemonEzquezy','S',3,'L'); --16

--LListes
	
insert into LLISTA (lis_id,lis_durada) values (15,0);
insert into LLISTA (lis_id,lis_durada) values (16,0);


--albums--

insert into ALBUM (alb_id,alb_any_creacio,alb_durada) values(13,2001,0);
insert into ALBUM (alb_id,alb_any_creacio,alb_durada) values(14,2021,0);


--cançons
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (1,1988,1,180);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (2,2000,3,285);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (3,2001,2,380);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (4,2002,5,180);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (5,2003,4,480);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (6,2004,8,380);

insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (7,2005,7,180);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (8,2006,6,180);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (9,2003,4,480);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (10,2004,8,380);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (11,2005,7,180);
insert into CANCO (can_id,can_any_creacio,can_interpret,can_durada) values (12,2006,6,180);

--LListes contingut--

insert into LLISTA_CONTINGUT (lic_id_llista,lic_id_PRODUCTE,lic_pos) values (15,13,1);
insert into LLISTA_CONTINGUT (lic_id_llista,lic_id_PRODUCTE,lic_pos) values (15,7,2);
insert into LLISTA_CONTINGUT (lic_id_llista,lic_id_PRODUCTE,lic_pos) values (15,8,3);

insert into LLISTA_CONTINGUT (lic_id_llista,lic_id_PRODUCTE,lic_pos) values (16,14,1);
insert into LLISTA_CONTINGUT (lic_id_llista,lic_id_PRODUCTE,lic_pos) values (16,5,2);
insert into LLISTA_CONTINGUT (lic_id_llista,lic_id_PRODUCTE,lic_pos) values (16,6,3);
	
	
--albums contingut--
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (13,1,1);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (13,2,2);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (13,3,3);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (13,4,4);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (13,5,5);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (13,6,6);

insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (14,7,1);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (14,8,2);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (14,9,3);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (14,10,4);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (14,11,5);
insert into ALBUM_CONTINGUT (alc_id_album,alc_id_canco,alc_pos) values (14,12,6);


---	H_GRUP

insert into H_GRUP (hgp_id_artgru,hgp_id_artind,hgp_data_inici) values (7,1,TO_DATE('09/08/1979', 'DD/MM/YYYY'));
insert into H_GRUP (hgp_id_artgru,hgp_id_artind,hgp_data_inici) values (7,6,TO_DATE('09/08/1979', 'DD/MM/YYYY'));

insert into H_GRUP (hgp_id_artgru,hgp_id_artind,hgp_data_inici,hgp_data_final) values (8,3,TO_DATE('09/08/1980', 'DD/MM/YYYY'),TO_DATE('09/08/1990', 'DD/MM/YYYY'));
insert into H_GRUP (hgp_id_artgru,hgp_id_artind,hgp_data_inici,hgp_data_final) values (8,5,TO_DATE('09/08/1980', 'DD/MM/YYYY'),TO_DATE('09/08/1990', 'DD/MM/YYYY'));
		

--reproduccions

insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (1,TO_DATE('11/03/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),1);
insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (1,TO_DATE('12/04/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),13);
insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (1,TO_DATE('13/05/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),15);

insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (2,TO_DATE('14/04/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),2);
insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (2,TO_DATE('15/04/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),14);
insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (2,TO_DATE('16/04/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),16);

insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (3,TO_DATE('14/04/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),3);
insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (3,TO_DATE('15/04/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),14);
insert into REPRODUCCIO (rep_id_client,rep_moment_temporal,rep_id_producte) values (3,TO_DATE('16/04/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),15);
